# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: arr-stack
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://bjw-s-labs.github.io/helm-charts/
    chart: sonarr
    targetRevision: 1.5.1
    helm:
      values: |
        env:
          TZ: "Europe/Warsaw"
        service:
          type: LoadBalancer
        ingress:
          main:
            enabled: true
        persistence:
          config:
            enabled: true
          media:
            enabled: true
            mountPath: /media
        metrics:
          enabled: true
          serviceMonitor:
            interval: 30s
            scrapeTimeout: 1m
            labels: {}
          prometheusRule:
            enabled: true
            groups:
            - name: sonarr.rules
              rules:
              - alert: SonarrDown
                expr: up{job="sonarr"} == 0
                for: 5m
                labels:
                  severity: critical
                annotations:
                  summary: "Sonarr is down"
                  description: "Sonarr instance is not reachable."
        exporter:
          image:
            repository: ghcr.io/onedr0p/exportarr
            tag: v2.2.0
            pullPolicy: IfNotPresent
          env:
            port: 9794
            additionalMetrics: false 
            unknownQueueItems: false  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

# ############################## END OF prometheus.yaml ####################################
