# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual-budget
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: budget
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://kriegalex.github.io/k8s-charts/
    chart: actual-budget
    targetRevision: 0.2.3
    helm:
      values: |
        env:
          TZ: "Europe/Warsaw"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          url: "budget.katedra.kys" 
          annotations:
            cert-manager.io/cluster-issuer: "selfsigned-issuer"
        replicaCount: 3
        persistence:
          enabled: true
          existingClaim: "actualbudget"
          mountPath: /data
          storageClassName: actualbudget-storage
          size: 1Gi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

# ############################## END OF prometheus.yaml ####################################
