# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: arr-stack
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://jellyfin.github.io/jellyfin-helm/
    chart: jellyfin
    targetRevision: 2.3.0
    helm:
      values: |
        ingress:
          enabled: true
          className: "nginx"
          hosts:
            - host: jellyfin.katedra.kys
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: wildcard-katedra-tls
              hosts:
                - jellyfin.katedra.kys
        persistence:
          config:
            enabled: true
            existingClaim: "jellyfin-config"
          media:
            enabled: true
            existingClaim: "jellyfin-media"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

# ############################## END OF prometheus.yaml ####################################
