# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: arr-stack
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://jellyfin.github.io/jellyfin-helm/
    chart: jellyfin
    targetRevision: 2.3.0
    helm:
      values: |
        service:
          enabled: true
          type: LoadBalancer
        volumes:
          - name: config
            persistentVolumeClaim:
              claimName: jellyfin-config
          - name: media
            persistentVolumeClaim:
              claimName: jellyfin-media
        volumeMounts:
          - name: config
            mountPath: /config
          - name: media
            mountPath: /media
        metrics:
          enabled: true
          serviceMonitor:
            interval: 30s
            scrapeTimeout: 1m
            labels: {}
          prometheusRule:
            enabled: true
            groups:
            - name: jellyfin.rules
              rules:
              - alert: JellyfinDown
                expr: up{job="jellyfin"} == 0
                for: 5m
                labels:
                  severity: critical
                annotations:
                  summary: "Jellyfin is down"
                  description: "Jellyfin instance is not reachable."
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

# ############################## END OF prometheus.yaml ####################################
