---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
    path: .
    targetRevision: 75.18.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - jsonPointers:
    - /spec/volumeName
    - /spec/storageClassName
    kind: PersistentVolumeClaim
