---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 75.18.1
    helm:
      values: |
        crds:
          enabled: false
        prometheus:
          ingress:
            enabled: true
            ingressClassName: "nginx"
            hosts:
              - prometheus.katedra.kys
            tls:
              - secretName: wildcard-katedra-tls
                hosts:
                  - prometheus.katedra.kys
        grafana:
          enabled: true
          defaultDashboardsTimezone: "browser"
          ingress:
            enabled: true
            ingressClassName: "nginx"
            hosts: 
              - grafana.katedra.kys
            tls:
              - secretName: wildcard-katedra-tls
                hosts:
                  - grafana.katedra.kys
        alertmanager:
          alertmanagerSpec:
            externalUrl: https://alertmanager.katedra.kys
          ingress:
            enabled: true
            ingressClassName: "nginx"
            hosts:
              - alertmanager.katedra.kys
            tls:
              - secretName: wildcard-katedra-tls
                hosts:
                  - alertmanager.katedra.kys
        nodeExporter:
          enabled: true
        prometheusOperator:
          enabled: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
