apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media-servarr
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - list:
      elements:
      - name: bazarr
        targetRevision: 0.8.3
      - name: flaresolverr
        targetRevision: 0.7.3
      - name: homarr
        targetRevision: 0.11.0
      - name: jellyfin
        targetRevision: 0.7.2
      - name: jellyseerr
        targetRevision: 0.5.0
      - name: lidarr
        targetRevision: 0.13.3
      - name: prowlarr
        targetRevision: 0.15.1
      - name: radarr
        targetRevision: 0.17.1
      - name: sonarr
        targetRevision: 0.8.4
      - name: transmission
        targetRevision: 0.8.3
  template:
    metadata:
      name: '{{.name}}-media-servarr'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://media-servarr.shw.al/charts
        targetRevision: '{{.targetRevision}}'
        path: '{{ .name }}'
        helm:
          valueFiles:
          - 'applications/values/media-servarr/{{.name}}.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: servarr
    syncPolicy:
      automated:
        prune: false
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
