---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts/
    chart: prometheus
    targetRevision: 19.7.2
    helm:
      values: |
        server:
          baseURL: "https://prometheus.katedra.kys"
          podSecurityContext:
              runAsUser: 65534
              runAsNonRoot: true
              runAsGroup: 65534
              fsGroup: 65534
          persistentVolume:
            enabled: true
            existingClaim: "prometheus-server"
            mountPath: /mnt/data/prometheus
          ingress:
            enabled: true
            ingressClassName: "nginx"
            hosts:
              - prometheus.katedra.kys
            tls:
              - secretName: wildcard-katedra-tls
                hosts:
                  - prometheus.katedra.kys 
        alertmanager:
          enabled: false 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

# ############################## END OF prometheus.yaml ####################################
