apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: servarr
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.gabe565.com
    chart: qbittorrent
    targetRevision: 0.4.1
    helm:
      values: |
        persistence:
          config:
            enabled: true
            size: 1Gi
            storageClass: "nfs-csi"
            retain: true
            accessMode: ReadWriteOnce
        service:
          main:
            ports:
              http:
                port: 8080
          bittorrent:
            enabled: true 
            ports:
              bittorrent:
                enabled: true
                port: 6881
                protocol: TCP
        ingress:
          main:
            enabled: true
            className: nginx
            hosts: 
              - host: qbittorrent.katedra.cc
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: katedra.cc
                hosts:
                  - qbittorrent.katedra.cc
        env:
          TZ: 'Europe/Warsaw'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
