# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: arr-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/azezej/homelab-charts
    targetRevision: HEAD
    path: applications/radarr
    helm:
      chart: app-template
      repoURL: https://bjw-s-labs.github.io/helm-charts
      parameters:
      - name: image.repository
        value: ghcr.io/linuxserver/radarr
      - name: image.tag
        value: latest
      - name: service.main.ports.http.port
        value: "7878"
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

# ############################## END OF radarr.yaml ####################################
