# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: arr-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://k8s-home-lab.github.io/helm-charts/
    chart: radarr
    targetRevision: 19.7.2
    helm:
      values: |
        env:
          TZ: "Europe/Warsaw"
        service:
          type: LoadBalancer
        ingress:
          main:
            enabled: true
        exporter:
          image:
            repository: ghcr.io/onedr0p/exportarr
            tag: v2.2.0
            pullPolicy: IfNotPresent
          env:
            port: 9793
            additionalMetrics: false 
            unknownQueueItems: false
        persistence:
          config:
            enabled: true
          media:
            enabled: true
            mountPath: /media
        metrics:
          enabled: true
          serviceMonitor:
            interval: 30s
            scrapeTimeout: 1m
            labels: {}
          prometheusRule:
            enabled: true
            groups:
            - name: radarr.rules
              rules:
              - alert: RadarrDown
                expr: up{job="radarr"} == 0
                for: 5m
                labels:
                  severity: critical
                annotations:
                  summary: "Radarr is down"
                  description: "Radarr instance is not reachable."
              - alert: RadarrHighCPUUsage
                expr: rate(container_cpu_usage_seconds_total{job="radarr"}[5m])
                for: 5m
                labels:
                  severity: warning
                annotations:
                  summary: "High CPU usage in Radarr"
                  description: "Radarr is using high CPU resources."
              - alert: RadarrHighMemoryUsage
                expr: container_memory_usage_bytes{job="radarr"} > 500 * 1024 * 1024
                for: 5m
                labels:
                  severity: warning
                annotations:
                  summary: "High memory usage in Radarr"
                  description: "Radarr is using high memory resources."
              - alert: RadarrDiskSpaceLow
                expr: (node_filesystem_avail_bytes{job="radarr"} / node_filesystem_size_bytes{job="radarr"}) < 0.1
                for: 5m
                labels:
                  severity: warning
                annotations:
                  summary: "Low disk space in Radarr"
                  description: "Radarr is running low on disk space."
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

# ############################## END OF radarr.yaml ####################################
