# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: arr-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts/
    chart: app-template
    targetRevision: 4.2.0
    helm:
      values: |
        image:
          repository: ghcr.io/linuxserver/radarr
          tag: latest
        service:
          main:
            ports:
              http:
                port: 7878
        env:
          TZ: "UTC"
          PUID: "1000"
          PGID: "1000"
        persistence:
          config:
            enabled: true
            existingClaim: jellyfin-config
          media:
            enabled: true
            existingClaim: jellyfin-media 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

# ############################## END OF radarr.yaml ####################################
