apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: password-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://guerzon.github.io/vaultwarden
    chart: vaultwarden
    targetRevision: 0.32.4
    helm:
      values: |
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          class: "nginx"
          hostname: https://vaultwarden.katedra.kys
          additionalHostnames:
            - https://vw.katedra.kys
          allowList: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
