apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vaultwarden
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://guerzon.github.io/vaultwarden
    chart: vaultwarden
    targetRevision: 0.32.4
    helm:
      values: |
        domain: "https://vaultwarden.katedra.kys"
        ingress:
          enabled: true
          class: "nginx"
          nginxIngressAnnotations: true
          tlsSecret: wildcard-katedra-tls
          hostname: vaultwarden.katedra.kys
          additionalHostnames:
            - vw.katedra.kys
            - vaultwarden.katedra.cc
            - vw.katedra.cc
          allowList: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
