apiVersion: v1
kind: PersistentVolume
metadata:
  name: actualbudget
  namespace: budget
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: actualbudget-storage
  local:
    path: /mnt/data/actualbudget
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker-afrodyta-3.katedra.kys
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---


