apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget
  namespace: budget
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: actualbudget-storage
