apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/prometheus  # Or NFS, or other backend
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-storage
