# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/azezej/homelab-charts.git
    targetRevision: main
  - repoURL: https://prometheus-community.github.io/helm-charts/
    chart: prometheus
    targetRevision: 19.7.2
    helm:
      values: |
        server:
          service:
            enabled: true
            type: LoadBalancer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

# ############################## END OF prometheus.yaml ####################################
