apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-stack-pv
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /media
  persistentVolumeReclaimPolicy: Retain
  storageClassName: arr-stack-sc
