---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-pvc
  namespace: arr-stack 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: arr-stack-sc
  volumeName: arr-stack-pv
